name: Capstone temperatures

on:
  workflow_dispatch:
    inputs:
      year:
        required: true
        default: '1984'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Generate ${{ github.event.inputs.year }} images
      working-directory: capstone/observatory
      run: sbt "run ${{ github.event.inputs.year }}"
    - name: Package
      working-directory: capstone/observatory
      run: zip -r ${{ github.event.inputs.year }} target/temperatures
    - name: Publish ${{ github.event.inputs.year }}
      uses: actions/upload-artifact@v2
      with:
        name: Tiles ${{ github.event.inputs.year }}
        path: capstone/observatory/${{ github.event.inputs.year }}.zip
      
